# Copyright 2026 Phillip Cloud
# Licensed under the Apache License, Version 2.0

baseURL = "/"
title = "micasa"
languageCode = "en-us"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "manni"
noClasses = false

[params]
description = "A terminal UI for tracking everything about your home. Single SQLite file. No cloud. No account. No subscriptions."
